export const ALBUMS = [
  {
    id: "1",
    rank: "01",
    title: "Certified",
    artist: "Burna Boy",
    year: "2020",
    plays: 23,
  },
  {
    id: "2",
    rank: "02",
    title: "Made in Lagos",
    artist: "Wizkid",
    year: "2020",
    plays: 18,
  },
  {
    id: "3",
    rank: "03",
    title: "Rave & Roses",
    artist: "Rema",
    year: "2022",
    plays: 15,
  },
  {
    id: "4",
    rank: "04",
    title: "A Good Time",
    artist: "Davido",
    year: "2019",
    plays: 12,
  },
  {
    id: "5",
    rank: "05",
    title: "Twice as Tall",
    artist: "Burna Boy",
    year: "2020",
    plays: 10,
  },
  {
    id: "6",
    rank: "06",
    title: "Apollo",
    artist: "Fireboy DML",
    year: "2019",
    plays: 8,
  },
];