export const tracks = [
  {
    id: "1",
    rank: "01",
    track: "City Boys",
    artist: "Burna Boy",
    duration: "3:45",
    plays: 50,
    emoji: "🎧",
  },
  {
    id: "2",
    rank: "02",
    track: "Essence",
    artist: "Wizkid ft. Tems",
    duration: "4:02",
    plays: 42,
    emoji: "🎵",
  },
  {
    id: "3",
    rank: "03",
    track: "Calm Down",
    artist: "Rema & Selena Gomez",
    duration: "3:59",
    plays: 38,
    emoji: "🎧",
  },
  {
    id: "4",
    rank: "04",
    track: "Last Last",
    artist: "Burna Boy",
    duration: "2:47",
    plays: 35,
    emoji: "🎤",
  },
  {
    id: "5",
    rank: "05",
    track: "Free Mind",
    artist: "Tems",
    duration: "3:33",
    plays: 29,
    emoji: "🎼",
  },
  {
    id: "6",
    rank: "06",
    track: "Ye",
    artist: "Burna Boy",
    duration: "3:11",
    plays: 24,
    emoji: "🎶",
  },
  {
    id: "7",
    rank: "07",
    track: "Sungba",
    artist: "Davido",
    duration: "3:20",
    plays: 45,
    emoji: "🎵",
  },
  {
    id: "8",
    rank: "08",
    track: "Calm Down",
    artist: "Rema",
    duration: "3:59",
    plays: 38,
    emoji: "🎧",
  },
  {
    id: "9",
    rank: "09",
    track: "Rush",
    artist: "Wizkid",
    duration: "2:45",
    plays: 32,
    emoji: "🎤",
  },
  {
    id: "10",
    rank: "10",
    track: "Finesse",
    artist: "Asake",
    duration: "3:10",
    plays: 28,
    emoji: "🎼",
  },
];